### ISSUE TITLE
Typo that prevents optional csv from loading

### ISSUE THREAD

**Issue by joeldmott** [learn-co-curriculum/dsc-complete-regression-lab#2]
## Link to Canvas

https://learning.flatironschool.com/courses/5309/assignments/176714?module_item_id=389048

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [x ] Other (explain below)

### Source

```
Level up - Optional
Load the "heightweight.csv" dataset. Use the height as an independent and weight as a dependent variable and draw a regression line to data using your code above. Calculate your R-Squared value for the model and try to predict new values of y.
```

### Concern

The csv file name has a capitalized "W" for "Weight," so unless you make that change when you read it in, it won't load.

## What OS Are You Using?

- [ ] OS X
- [ x] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
Fixed.
